name: Comment Changesets PR Status

on:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  pr-status:
    if: ${{ !startsWith(github.head_ref, 'changeset-release/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      comment-body: ${{ steps.pr-status.outputs.comment-body }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Generate PR status
        id: pr-status
        uses: changesets/action/pr-status@v2

  pr-comment:
    needs: pr-status
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: changesets/action/pr-comment@v2
        with:
          body: ${{ needs.pr-status.outputs.comment-body }}
