name: Publish

on:
  push:
    branches:
      - main

# Reset permissions and grant them per job.
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  mode:
    runs-on: ubuntu-latest
    outputs:
      mode: ${{ steps.changesets-mode.outputs.mode }}
      publish-plan-artifact-id: ${{ steps.changesets-mode.outputs.publish-plan-artifact-id }}
    permissions:
      contents: read
    steps:
      - name: 🔷 Checkout
        uses: actions/checkout@v7
      - name: 🟢 Setup bun
        uses: oviirup/actions/bun@v1
        with:
          node-version: 24
          install: true
      - name: 🔧 Select changesets mode
        id: changesets-mode
        uses: changesets/action/select-mode@v2
  version:
    if: needs.mode.outputs.mode == 'version'
    needs: mode
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🔷 Checkout
        uses: actions/checkout@v7
      - name: 🟢 Setup bun
        uses: oviirup/actions/bun@v1
        with:
          node-version: 24
          install: true
      - name: 🏷️ Update version
        id: version
        uses: changesets/action/version@v2
        with:
          script: bun changeset version
          commit-message: "✅ chore: update version"
          pr-title: "✅ chore: update version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pack:
    if: needs.mode.outputs.mode == 'publish'
    needs: mode
    runs-on: ubuntu-latest
    outputs:
      pack-dir-artifact-id: ${{ steps.pack.outputs.pack-dir-artifact-id }}
    permissions:
      contents: read
    steps:
      - name: 🔷 Checkout
        uses: actions/checkout@v7
      - name: 🟢 Setup bun
        uses: oviirup/actions/bun@v1
        with:
          node-version: 24
          install: true
      - name: 📦 Pack artifacts
        id: pack
        uses: changesets/action/pack@v2
        with:
          publish-plan-artifact-id: ${{ needs.mode.outputs.publish-plan-artifact-id }}

  publish:
    needs: pack
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🔷 Checkout
        uses: actions/checkout@v7
      - name: 🟢 Setup bun
        uses: oviirup/actions/bun@v1
        with:
          node-version: 24
          install: true
      - name: 📦 Run build
        run: bun run build
      - name: ⚙️ Publish packages
        id: publish
        uses: changesets/action/publish@v2
        with:
          pack-dir-artifact-id: ${{ needs.pack.outputs.pack-dir-artifact-id }}
          create-github-releases: true
          push-git-tags: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
